name: qr_new
description: A new Flutter project.


publish_to: 'Tayyip GUZEL' 


version: 1.0.0+4

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  supabase_flutter: ^0.3.1
  mobile_scanner: ^1.1.0
  google_fonts: ^2.3.2
  flutter_svg: ^1.0.3
  settings_ui: ^2.0.2
  lottie: ^1.3.0
  get_it: ^7.2.0
  permission_handler: ^9.2.0
  easy_localization: ^3.0.1
  hive_flutter: ^1.1.0
  firebase_messaging: ^11.4.1
  firebase_core: ^1.17.1
  flutter_local_notifications: ^9.5.3+1
  native_notify: ^0.0.13

  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.0+1
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_qr.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/ic_qr.png


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
    - assets/lang/


